platform: Any CPU
image: Visual Studio 2017

#restore NuGet packegesbefore build
before_build: 
 - dotnet restore books_store/book_store_backend.sln

build:
  verbosity: normal
  
test_script:
#Generate report for unit tests
- OpenCover.Console.exe 
    -register:user 
    -target:"dotnet.exe" 
    -targetargs:"test books_store\book_store.tests\book_store.tests.csproj /p:CollectCoverage=true"
    -filter:"+[book_store_backend]* -[book_store.tests]*"
    -output:"coverage_unit.xml"
    -oldStyle
    
#Generate report for integration tests
- OpenCover.Console.exe 
    -register:user 
    -target:"dotnet.exe" 
    -targetargs:"test books_store\book_store.api_tests\book_store.api_integration_tests.csproj /p:CollectCoverage=true"
    -filter:"+[book_store_backend]* -[book_store.api_integration_tests]*"
    -output:"coverage_integration.xml"
    -oldStyle
    
# Upload test report to codecov.io
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage_unit.xml" -t "3aceb04d-c7be-4dc7-afc1-57807982f2cc"
      bash codecov.sh -f "coverage_integration.xml" -t "3aceb04d-c7be-4dc7-afc1-57807982f2cc"

artifacts:
- path: artifacts\**\*.*
