platform: Any CPU
image: Visual Studio 2017

#restore NuGet packegesbefore build
before_build: 
 - dotnet restore books_store/book_store_backend.sln

build:

test_script:
- OpenCover.Console.exe 
    -register:user 
    -target:"%xunit20%\xunit.console.x86.exe" 
    -targetargs:"books_store\book_store.tests\bin\Debug\netcoreapp2.2\book_store.tests.dll
                 books_store\book_store.api_tests\bin\Debug\netcoreapp2.2\book_store.api_integration_tests.dll
                 -noshadow"
    -output:"coverage.xml"
    -oldStyle
    
# use codecov bash script. Requires powershell and bash to be installed, which both are on the AppVeyor machine image
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t "3aceb04d-c7be-4dc7-afc1-57807982f2cc"