platform: Any CPU
image: Visual Studio 2017
branches:
  only:
  - develop
#restore NuGet packegesbefore build
before_build: 
 dotnet restore books_store/book_store_backend.sln

#package web application project for web deloy
build:
 project: books_store/book_store_backend.sln
