platform: Any CPU
image: Visual Studio 2017

#restore NuGet packegesbefore build
before_build: 
 dotnet restore books_store/book_store_backend.sln

#package web application project for web deloy
build:

test_script:
  - cmd: dotnet restore ./books_store/book_store.tests/book_store.tests.csproj --verbosity m
  - cmd: cd books_store/book_store.tests
  - cmd: dotnet test
  - cmd: cd books_store/book_store.api_tests
  - cmd: dotnet test
