configuration: Release
platform: Any CPU
#restore NuGet packegesbefore build
before_build: nuget restore books store/book store backend.sln
 
#package web application project for web deloy
build:
  publish_wap: true
